# Generated by Django 2.2.5 on 2020-07-07 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.IntegerField(blank=True)),
                ('pet_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=50)),
                ('park_location', models.CharField(max_length=100)),
                ('park_review', models.CharField(max_length=150)),
                ('park_thumbs', models.BooleanField(default=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfectWalk.Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfectWalk.User')),
            ],
            options={
                'ordering': ['park_location'],
            },
            managers=[
                ('Posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfectWalk.User'),
        ),
    ]
