# Generated by Django 2.2.5 on 2020-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfectWalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['park_name']},
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.IntegerField(),
        ),
    ]
