# Generated by Django 2.2.5 on 2020-07-09 22:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PerfectWalk', '0002_auto_20200707_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_visited',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
